<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-27T12:43:29+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.2',
    'version_db_installed' => '20180122213656',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1543317555,
        'latest_version' => '8.4.3',
    ],
];
