<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-27T12:17:04+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Boilerplate',
        ],
    ],
];
